global using System.ComponentModel.DataAnnotations;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using GameZone.Data;
global using GameZone.Models;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using Microsoft.EntityFrameworkCore;
global using GameZone.Setting;
global using GameZone.ViewModel;